### ISSUE TITLE
Can't get anything after load/use DB

### ISSUE THREAD

**Issue by LubeckHuaman** [epsilla-cloud/epsilla-python-client#43]
<img width="968" alt="image" src="https://github.com/epsilla-cloud/epsilla-python-client/assets/4401153/3fd136c4-dcc8-43e3-972f-6daa4bd9682a">

Even the Colab example isn't working

**Comment by richard-epsilla** [comment]
Thanks for pointing this out! We have fixed the demo

**Comment by richard-epsilla** [comment]
@incafox please let us know if the issue exists in your dev environment. It's due to pyepsilla and db version incompatibility. We need make sure the 2nd digit of pyepsilla version and db version matches

**Comment by LubeckHuaman** [comment]
its working now thanks!
